# Generated by Django 4.0.2 on 2022-06-04 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Key', models.CharField(max_length=1000)),
                ('mode', models.CharField(choices=[('Light', 'Light'), ('Dark', 'Dark')], default='Light', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.DateField()),
                ('islam', models.CharField(choices=[('A', 'Islam By Birth'), ('B', 'Convert'), ('C', 'Other')], max_length=100, null=True)),
                ('Basic_Knowledge', models.CharField(blank=True, choices=[('A', 'Basic'), ('B', 'Intermediary'), ('C', 'Advanced')], max_length=50, null=True)),
                ('NameofLastProphet', models.CharField(blank=True, choices=[('A', 'Prophet Isa'), ('B', 'Prophet Musa'), ('C', 'Prophet Muhammed'), ('D', 'Prophet Ibrahim')], max_length=50, null=True)),
                ('mode', models.CharField(choices=[('Light', 'Light'), ('Dark', 'Dark')], default='Light', max_length=10)),
                ('follow', models.ManyToManyField(related_name='follows', to='ask.Profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ProfUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('body', models.CharField(max_length=1000)),
                ('active', models.BooleanField(default=True)),
                ('Views', models.IntegerField(blank=True, default=0, null=True)),
                ('Support', models.ManyToManyField(blank=True, related_name='support', to='ask.Profile')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User', to='ask.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('body', models.CharField(max_length=1000)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('active', models.BooleanField(default=True)),
                ('dislike', models.ManyToManyField(blank=True, related_name='dislike', to='ask.Profile')),
                ('like', models.ManyToManyField(blank=True, related_name='like', to='ask.Profile')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question', to='ask.question')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replys', to='ask.answer')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userName', to='ask.profile')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
